export const twinAbi = [
  {
    type: "function",
    name: "watch",
    stateMutability: "nonpayable",
    inputs: [{ name: "target", type: "address" }],
    outputs: [],
  },
  {
    type: "event",
    name: "DualStatusSettled",
    inputs: [
      { name: "target", type: "address", indexed: true },
      { name: "scanOK", type: "bool", indexed: false },
      { name: "visionOK", type: "bool", indexed: false },
      { name: "dualOK", type: "bool", indexed: false },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "checkedAt", type: "uint64", indexed: false },
    ],
  },
  {
    type: "function",
    name: "watchBatch",
    stateMutability: "nonpayable",
    inputs: [{ name: "targets", type: "address[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "report",
    stateMutability: "nonpayable",
    inputs: [
      { name: "target", type: "address" },
      { name: "scanOK", type: "bool" },
      { name: "visionOK", type: "bool" },
      { name: "evidenceHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getCard",
    stateMutability: "view",
    inputs: [{ name: "target", type: "address" }],
    outputs: [
      { name: "watched", type: "bool" },
      { name: "settled", type: "bool" },
      { name: "scanOK", type: "bool" },
      { name: "visionOK", type: "bool" },
      { name: "isDualOK", type: "bool" },
      { name: "checkedAt", type: "uint64" },
      { name: "evidenceHash", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "dualOK",
    stateMutability: "view",
    inputs: [{ name: "target", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "watchedCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "watchedAt",
    stateMutability: "view",
    inputs: [{ name: "i", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "attestorA",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "attestorB",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
] as const;
